### ISSUE TITLE
Extension not loading on latest geyser, with latest build from here

### ISSUE THREAD

**Issue by Paceski** [GeyserExtensionists/GeyserModelEngine#23]
Not loading

![image](https://github.com/user-attachments/assets/c2ded519-a7fa-44d4-b99e-a83e2893ed57)

**Comment by zimzaza4** [comment]
GeyserModelEngine is spigot plugin
GeyserModelEnginePackGenerator is a Geyser extension

**Comment by zimzaza4** [comment]
Please read the README

**Comment by Paceski** [comment]
Appreciate it, didn't notice that. Thank you.
