### ISSUE TITLE
Extreme lag from GeyserModelEngine

### ISSUE THREAD

**Issue by sennby** [GeyserExtensionists/GeyserModelEngine#24]
https://spark.lucko.me/OjrT4Tu4oU

**Comment by zimzaza4** [comment]
try update

**Comment by sennby** [comment]
> try update

https://spark.lucko.me/dSNquUNUmD no luck

**Comment by zimzaza4** [comment]
huh strange, how many meg entities are spawned? did you try disable GeyserModelEngine?

**Comment by zimzaza4** [comment]
try update again

**Comment by sennby** [comment]
> try update again

Hey i wont be able to test as my dev was able to make a version of it fixed for me and I do not want to have to deal with it again. Hopefully someone else can test.

**Comment by sennby** [comment]
I decided to test the latest update. No lag so far - however, no bedrock players can see any models anymore.

**Comment by zimzaza4** [comment]
update geyserutils-geyser

**Comment by sennby** [comment]
> update geyserutils-geyser

Still bedrock can see no models.

**Comment by zimzaza4** [comment]
update GeyserModelEngine again?

**Comment by zimzaza4** [comment]
wait

**Comment by zimzaza4** [comment]
[GeyserModelEngine.zip](https://github.com/user-attachments/files/17740821/GeyserModelEngine.zip)
try this

**Comment by sennby** [comment]
Seems good!
